included:
  - Pulse
  - PulseTests
  - PulseUITests

excluded:
  - build
  - DerivedData
  - .build

disabled_rules:
  - statement_position
  - trailing_comma

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 120
  error: 140

file_length:
  warning: 500
  error: 500

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id

reporter: xcode

cache_path: .swiftlint_cache
